/**
 * BANCO DE DADOS POKÉMON STADIUM (GEN 1)
 */

// Tabela de Eficácia da Geração 1 (Atacante -> Defensor)
// 2.0 = Super Effective, 0.5 = Not Very Effective, 0.0 = No Effect
const GEN1_TYPE_CHART = {
    normal:   { rock: 0.5, ghost: 0 },
    fire:     { fire: 0.5, water: 0.5, grass: 2, ice: 2, bug: 2, rock: 0.5, dragon: 0.5 },
    water:    { fire: 2, water: 0.5, grass: 0.5, ground: 2, rock: 2, dragon: 0.5 },
    electric: { water: 2, electric: 0.5, grass: 0.5, ground: 0, flying: 2, dragon: 0.5 },
    grass:    { fire: 0.5, water: 2, grass: 0.5, poison: 0.5, ground: 2, flying: 0.5, bug: 0.5, rock: 2, dragon: 0.5 },
    ice:      { water: 0.5, grass: 2, ice: 0.5, ground: 2, flying: 2, dragon: 2 },
    fighting: { normal: 2, ice: 2, poison: 0.5, flying: 0.5, psychic: 0.5, bug: 0.5, rock: 2, ghost: 0 },
    poison:   { grass: 2, poison: 0.5, ground: 0.5, bug: 2, rock: 0.5, ghost: 0.5 }, // Bug era fraco a Poison na Gen 1
    ground:   { fire: 2, electric: 2, grass: 0.5, poison: 2, flying: 0, bug: 0.5, rock: 2 },
    flying:   { electric: 0.5, grass: 2, fighting: 2, bug: 2, rock: 0.5 },
    psychic:  { fighting: 2, poison: 2, psychic: 0.5 },
    bug:      { fire: 0.5, grass: 2, fighting: 0.5, poison: 2, flying: 0.5, psychic: 2, ghost: 0.5 }, // Poison era fraco a Bug na Gen 1
    rock:     { fire: 2, ice: 2, fighting: 0.5, ground: 0.5, flying: 2, bug: 2 },
    ghost:    { normal: 0, psychic: 0, ghost: 2 }, // Lembrete: Ghost não afetava Psychic na Gen 1 por bug, mas afetava Ghost
    dragon:   { dragon: 2 }
};

// Dados dos Golpes (Accuracy e Tipo)
const MOVES_DATA = {
    "Body Slam": {type: "normal", acc100: true}, "Double-edge": {type: "normal", acc100: true}, "Tackle": {type: "normal", acc100: true},
    "Leech Seed": {type: "grass", acc100: false}, "Toxic": {type: "poison", acc100: false}, "Mega Drain": {type: "grass", acc100: true},
    "Swords Dance": {type: "normal", acc100: true}, "Solar Beam": {type: "grass", acc100: true}, "Fire Blast": {type: "fire", acc100: false},
    "Growl": {type: "normal", acc100: true}, "Seismic Toss": {type: "fighting", acc100: true}, "Strength": {type: "normal", acc100: true},
    "Ember": {type: "fire", acc100: true}, "Mega Kick": {type: "normal", acc100: false}, "Blizzard": {type: "ice", acc100: false},
    "Dig": {type: "ground", acc100: true}, "Surf": {type: "water", acc100: true}, "Reflect": {type: "psychic", acc100: true},
    "Bide": {type: "normal", acc100: true}, "String Shot": {type: "bug", acc100: false}, "Poisonpowder": {type: "poison", acc100: false},
    "Take Down": {type: "normal", acc100: false}, "Hyper Beam": {type: "normal", acc100: false}, "Psywave": {type: "psychic", acc100: false},
    "Poison Sting": {type: "poison", acc100: true}, "Fury Attack": {type: "normal", acc100: false}, "Double Team": {type: "normal", acc100: true},
    "Fly": {type: "flying", acc100: true}, "Sky Attack": {type: "flying", acc100: false}, "Sand-attack": {type: "normal", acc100: true},
    "Quick Attack": {type: "normal", acc100: true}, "Thunder": {type: "electric", acc100: false}, "Hyper Fang": {type: "normal", acc100: false},
    "Swift": {type: "normal", acc100: true}, "Ice Beam": {type: "ice", acc100: true}, "Mimic": {type: "normal", acc100: true},
    "Peck": {type: "flying", acc100: true}, "Wrap": {type: "normal", acc100: false}, "Leer": {type: "normal", acc100: true},
    "Earthquake": {type: "ground", acc100: true}, "Thunder Wave": {type: "electric", acc100: true}, "Submission": {type: "fighting", acc100: false},
    "Thunderbolt": {type: "electric", acc100: true}, "Horn Drill": {type: "normal", acc100: false}, "Fissure": {type: "ground", acc100: false},
    "Double Kick": {type: "fighting", acc100: true}, "Horn Attack": {type: "normal", acc100: true}, "Bubblebeam": {type: "water", acc100: true},
    "Metronome": {type: "normal", acc100: true}, "Tri Attack": {type: "normal", acc100: true}, "Psychic": {type: "psychic", acc100: true},
    "Sing": {type: "normal", acc100: false}, "Supersonic": {type: "normal", acc100: false}, "Mega Punch": {type: "normal", acc100: false},
    "Stun Spore": {type: "grass", acc100: false}, "Flash": {type: "normal", acc100: false}, "Rest": {type: "psychic", acc100: true},
    "Low Kick": {type: "fighting", acc100: true}, "Karate Chop": {type: "normal", acc100: true}, "Counter": {type: "fighting", acc100: true},
    "Bite": {type: "normal", acc100: true}, "Doubleslap": {type: "normal", acc100: false}, "Hypnosis": {type: "psychic", acc100: false},
    "Acid": {type: "poison", acc100: true}, "Rock Slide": {type: "rock", acc100: false}, "Defense Curl": {type: "normal", acc100: true},
    "Substitute": {type: "normal", acc100: true}, "Headbutt": {type: "normal", acc100: true}, "Explosion": {type: "normal", acc100: true},
    "Clamp": {type: "water", acc100: false}, "Aurora Beam": {type: "ice", acc100: true}, "Confuse Ray": {type: "ghost", acc100: true},
    "Night Shade": {type: "ghost", acc100: true}, "Selfdestruct": {type: "normal", acc100: true}, "Dream Eater": {type: "psychic", acc100: true},
    "Egg Bomb": {type: "normal", acc100: false}, "Barrage": {type: "normal", acc100: false}, "Tail Whip": {type: "normal", acc100: true},
    "Smokescreen": {type: "normal", acc100: true}, "Splash": {type: "normal", acc100: true}, "Hydro Pump": {type: "water", acc100: false},
    "Skull Bash": {type: "normal", acc100: true}, "Transform": {type: "normal", acc100: true}, "Conversion": {type: "normal", acc100: true},
    "Sharpen": {type: "normal", acc100: true}, "Growth": {type: "normal", acc100: true}, "Meditate": {type: "psychic", acc100: true},
    "Agility": {type: "psychic", acc100: true}, "Pin Missile": {type: "bug", acc100: false}
};

// Database Pokémons
const POKEDEX = [
    {id: "001", name: "Bulbasaur", types: ["grass", "poison"], rentals: { pika_cup: { hp: 42, atk: 23, def: 23, spc: 28, spd: 22, moves: ["Leech Seed", "Double-edge", "Toxic", "Mega Drain"] }}},
    {id: "002", name: "Ivysaur", types: ["grass", "poison"], rentals: { pika_cup: { hp: 47, atk: 27, def: 28, spc: 33, spd: 27, moves: ["Swords Dance", "Leech Seed", "Body Slam", "Solar Beam"] }}},
    {id: "004", name: "Charmander", types: ["fire"], rentals: { pika_cup: { hp: 40, atk: 24, def: 22, spc: 24, spd: 28, moves: ["Fire Blast", "Growl", "Seismic Toss", "Strength"] }}},
    {id: "005", name: "Charmeleon", types: ["fire"], rentals: { pika_cup: { hp: 46, atk: 28, def: 26, spc: 28, spd: 33, moves: ["Swords Dance", "Ember", "Mega Kick", "Toxic"] }}},
    {id: "007", name: "Squirtle", types: ["water"], rentals: { pika_cup: { hp: 42, atk: 23, def: 28, spc: 24, spd: 22, moves: ["Tackle", "Blizzard", "Dig", "Surf"] }}},
    {id: "008", name: "Wartortle", types: ["water"], rentals: { pika_cup: { hp: 46, atk: 28, def: 33, spc: 28, spd: 26, moves: ["Body Slam", "Reflect", "Bide", "Surf"] }}},
    {id: "010", name: "Caterpie", types: ["bug"], rentals: { pika_cup: { hp: 42, atk: 18, def: 19, spc: 15, spd: 22, moves: ["String Shot", "Tackle"] }}},
    {id: "011", name: "Metapod", types: ["bug"], rentals: { pika_cup: { hp: 44, atk: 15, def: 25, spc: 16, spd: 18, moves: ["Tackle", "String Shot"] }}},
    {id: "012", name: "Butterfree", types: ["bug", "flying"], rentals: { pika_cup: { hp: 47, atk: 22, def: 24, spc: 33, spd: 30, moves: ["Poisonpowder", "Take Down", "Hyper Beam", "Psywave"] }}},
    {id: "013", name: "Weedle", types: ["bug", "poison"], rentals: { pika_cup: { hp: 41, atk: 19, def: 18, spc: 15, spd: 24, moves: ["String Shot", "Poison Sting"] }}},
    {id: "014", name: "Kakuna", types: ["bug", "poison"], rentals: { pika_cup: { hp: 42, atk: 16, def: 24, spc: 16, spd: 19, moves: ["String Shot", "Poison Sting"] }}},
    {id: "015", name: "Beedrill", types: ["bug", "poison"], rentals: { pika_cup: { hp: 48, atk: 33, def: 21, spc: 22, spd: 31, moves: ["Fury Attack", "Hyper Beam", "Double Team", "Swords Dance"] }}},
    {id: "016", name: "Pidgey", types: ["normal", "flying"], rentals: { pika_cup: { hp: 41, atk: 22, def: 21, spc: 19, spd: 26, moves: ["Reflect", "Double-edge", "Fly", "Toxic"] }}},
    {id: "017", name: "Pidgeotto", types: ["normal", "flying"], rentals: { pika_cup: { hp: 48, atk: 27, def: 25, spc: 24, spd: 30, moves: ["Sky Attack", "Sand-attack", "Take Down", "Quick Attack"] }}},
    {id: "019", name: "Rattata", types: ["normal"], rentals: { pika_cup: { hp: 38, atk: 26, def: 19, spc: 16, spd: 30, moves: ["Thunder", "Dig", "Quick Attack", "Blizzard"] }}},
    {id: "020", name: "Raticate", types: ["normal"], rentals: { pika_cup: { hp: 45, atk: 33, def: 27, spc: 24, spd: 38, moves: ["Hyper Fang", "Swift", "Toxic", "Ice Beam"] }}},
    {id: "021", name: "Spearow", types: ["normal", "flying"], rentals: { pika_cup: { hp: 41, atk: 27, def: 18, spc: 18, spd: 30, moves: ["Double-edge", "Mimic", "Double Team", "Fly"] }}},
    {id: "022", name: "Fearow", types: ["normal", "flying"], rentals: { pika_cup: { hp: 48, atk: 36, def: 28, spc: 27, spd: 39, moves: ["Fly", "Mimic", "Double Team", "Peck"] }}},
    {id: "023", name: "Ekans", types: ["poison"], rentals: { pika_cup: { hp: 39, atk: 27, def: 22, spc: 21, spd: 25, moves: ["Wrap", "Leer", "Poison Sting", "Earthquake"] }}},
    {id: "025", name: "Pikachu", types: ["electric"], rentals: { pika_cup: { hp: 39, atk: 25, def: 18, spc: 24, spd: 36, moves: ["Quick Attack", "Thunder Wave", "Submission", "Thunderbolt"] }}},
    {id: "026", name: "Raichu", types: ["electric"], rentals: { pika_cup: { hp: 47, atk: 36, def: 25, spc: 36, spd: 39, moves: ["Thunder", "Growl", "Thunder Wave", "Seismic Toss"] }}},
    {id: "027", name: "Sandshrew", types: ["ground"], rentals: { pika_cup: { hp: 44, atk: 31, def: 34, spc: 18, spd: 21, moves: ["Sand-attack", "Swords Dance", "Earthquake", "Submission"] }}},
    {id: "029", name: "Nidoran♀", types: ["poison"], rentals: { pika_cup: { hp: 45, atk: 23, def: 24, spc: 21, spd: 21, moves: ["Toxic", "Body Slam", "Thunder", "Blizzard"] }}},
    {id: "030", name: "Nidorina", types: ["poison"], rentals: { pika_cup: { hp: 50, atk: 27, def: 29, spc: 25, spd: 26, moves: ["Toxic", "Horn Drill", "Ice Beam", "Take Down"] }}},
    {id: "031", name: "Nidoqueen", types: ["poison", "ground"], rentals: { pika_cup: { hp: 56, atk: 33, def: 35, spc: 31, spd: 32, moves: ["Fissure", "Reflect", "Double Kick", "Surf"] }}},
    {id: "032", name: "Nidoran♂", types: ["poison"], rentals: { pika_cup: { hp: 43, atk: 26, def: 21, spc: 21, spd: 24, moves: ["Blizzard", "Toxic", "Thunderbolt", "Body Slam"] }}},
    {id: "033", name: "Nidorino", types: ["poison"], rentals: { pika_cup: { hp: 47, atk: 30, def: 26, spc: 25, spd: 28, moves: ["Horn Drill", "Horn Attack", "Ice Beam", "Double Kick"] }}},
    {id: "034", name: "Nidoking", types: ["poison", "ground"], rentals: { pika_cup: { hp: 53, atk: 36, def: 32, spc: 31, spd: 34, moves: ["Poison Sting", "Double Kick", "Earthquake", "Bubblebeam"] }}},
    {id: "035", name: "Clefairy", types: ["normal"], rentals: { pika_cup: { hp: 50, atk: 22, def: 23, spc: 27, spd: 19, moves: ["Thunder Wave", "Metronome", "Tri Attack", "Psychic"] }}},
    {id: "036", name: "Clefable", types: ["normal"], rentals: { pika_cup: { hp: 57, atk: 30, def: 31, spc: 34, spd: 27, moves: ["Metronome", "Tri Attack", "Sing", "Double Team"] }}},
    {id: "037", name: "Vulpix", types: ["fire"], rentals: { pika_cup: { hp: 40, atk: 21, def: 21, spc: 28, spd: 28, moves: ["Double-edge", "Fire Blast", "Double Team", "Dig"] }}},
    {id: "038", name: "Ninetales", types: ["fire"], rentals: { pika_cup: { hp: 51, atk: 32, def: 31, spc: 39, spd: 39, moves: ["Dig", "Ember", "Reflect", "Hyper Beam"] }}},
    {id: "039", name: "Jigglypuff", types: ["normal"], rentals: { pika_cup: { hp: 63, atk: 22, def: 15, spc: 16, spd: 15, moves: ["Sing", "Body Slam", "Thunder Wave", "Ice Beam"] }}},
    {id: "040", name: "Wigglytuff", types: ["normal"], rentals: { pika_cup: { hp: 71, atk: 30, def: 22, spc: 24, spd: 22, moves: ["Thunder", "Mega Punch", "Double Team", "Sing"] }}},
    {id: "041", name: "Zubat", types: ["poison", "flying"], rentals: { pika_cup: { hp: 41, atk: 22, def: 19, spc: 21, spd: 25, moves: ["Supersonic", "Swift", "Mega Drain", "Toxic"] }}},
    {id: "043", name: "Oddish", types: ["grass", "poison"], rentals: { pika_cup: { hp: 42, atk: 24, def: 25, spc: 31, spd: 18, moves: ["Toxic", "Swords Dance", "Mega Drain", "Take Down"] }}},
    {id: "046", name: "Paras", types: ["bug", "grass"], rentals: { pika_cup: { hp: 39, atk: 30, def: 25, spc: 25, spd: 16, moves: ["Stun Spore", "Dig", "Mega Drain", "Take Down"] }}},
    {id: "048", name: "Venonat", types: ["bug", "poison"], rentals: { pika_cup: { hp: 47, atk: 25, def: 24, spc: 21, spd: 22, moves: ["Supersonic", "Psychic", "Flash", "Double-edge"] }}},
    {id: "050", name: "Diglett", types: ["ground"], rentals: { pika_cup: { hp: 32, atk: 25, def: 16, spc: 22, spd: 37, moves: ["Earthquake", "Double Team", "Take Down", "Fissure"] }}},
    {id: "052", name: "Meowth", types: ["normal"], rentals: { pika_cup: { hp: 41, atk: 22, def: 19, spc: 21, spd: 36, moves: ["Double Team", "Thunderbolt", "Body Slam", "Rest"] }}},
    {id: "054", name: "Psyduck", types: ["water"], rentals: { pika_cup: { hp: 44, atk: 24, def: 23, spc: 24, spd: 25, moves: ["Bubblebeam", "Blizzard", "Dig", "Mimic"] }}},
    {id: "056", name: "Mankey", types: ["fighting"], rentals: { pika_cup: { hp: 41, atk: 33, def: 19, spc: 19, spd: 30, moves: ["Low Kick", "Karate Chop", "Dig", "Counter"] }}},
    {id: "058", name: "Growlithe", types: ["fire"], rentals: { pika_cup: { hp: 45, atk: 30, def: 22, spc: 24, spd: 27, moves: ["Dig", "Fire Blast", "Double-edge", "Reflect"] }}},
    {id: "059", name: "Arcanine", types: ["fire"], rentals: { pika_cup: { hp: 56, atk: 42, def: 33, spc: 33, spd: 37, moves: ["Dig", "Bite", "Ember", "Double Team"] }}},
    {id: "060", name: "Poliwag", types: ["water"], rentals: { pika_cup: { hp: 41, atk: 24, def: 21, spc: 21, spd: 36, moves: ["Surf", "Body Slam", "Blizzard", "Toxic"] }}},
    {id: "061", name: "Poliwhirl", types: ["water"], rentals: { pika_cup: { hp: 48, atk: 28, def: 28, spc: 24, spd: 36, moves: ["Surf", "Double-edge", "Metronome", "Earthquake"] }}},
    {id: "062", name: "Poliwrath", types: ["water", "fighting"], rentals: { pika_cup: { hp: 56, atk: 34, def: 37, spc: 30, spd: 30, moves: ["Surf", "Doubleslap", "Metronome", "Hypnosis"] }}},
    {id: "063", name: "Abra", types: ["psychic"], rentals: { pika_cup: { hp: 36, atk: 15, def: 13, spc: 40, spd: 36, moves: ["Psychic", "Thunder Wave", "Seismic Toss", "Reflect"] }}},
    {id: "064", name: "Kadabra", types: ["psychic"], rentals: { pika_cup: { hp: 41, atk: 19, def: 18, spc: 45, spd: 40, moves: ["Psychic", "Metronome", "Double Team", "Seismic Toss"] }}},
    {id: "065", name: "Alakazam", types: ["psychic"], rentals: { pika_cup: { hp: 45, atk: 24, def: 22, spc: 49, spd: 45, moves: ["Psywave", "Metronome", "Thunder Wave", "Mega Punch"] }}},
    {id: "066", name: "Machop", types: ["fighting"], rentals: { pika_cup: { hp: 50, atk: 33, def: 24, spc: 19, spd: 19, moves: ["Karate Chop", "Submission", "Fire Blast", "Bide"] }}},
    {id: "069", name: "Bellsprout", types: ["grass", "poison"], rentals: { pika_cup: { hp: 44, atk: 31, def: 19, spc: 30, spd: 21, moves: ["Growth", "Take Down", "Mega Drain", "Reflect"] }}},
    {id: "072", name: "Tentacool", types: ["water", "poison"], rentals: { pika_cup: { hp: 41, atk: 21, def: 19, spc: 39, spd: 30, moves: ["Surf", "Acid", "Supersonic", "Toxic"] }}},
    {id: "073", name: "Tentacruel", types: ["water", "poison"], rentals: { pika_cup: { hp: 53, atk: 30, def: 28, spc: 45, spd: 39, moves: ["Supersonic", "Wrap", "Toxic", "Mega Drain"] }}},
    {id: "074", name: "Geodude", types: ["rock", "ground"], rentals: { pika_cup: { hp: 41, atk: 33, def: 39, spc: 18, spd: 15, moves: ["Mega Punch", "Earthquake", "Rock Slide", "Defense Curl"] }}},
    {id: "077", name: "Ponyta", types: ["fire"], rentals: { pika_cup: { hp: 44, atk: 34, def: 25, spc: 28, spd: 36, moves: ["Fire Blast", "Horn Drill", "Reflect", "Swift"] }}},
    {id: "079", name: "Slowpoke", types: ["water", "psychic"], rentals: { pika_cup: { hp: 56, atk: 28, def: 28, spc: 21, spd: 13, moves: ["Psychic", "Surf", "Flash", "Dig"] }}},
    {id: "081", name: "Magnemite", types: ["electric"], rentals: { pika_cup: { hp: 36, atk: 19, def: 30, spc: 37, spd: 22, moves: ["Thunder Wave", "Thunderbolt", "Swift", "Substitute"] }}},
    {id: "083", name: "Farfetch'd", types: ["normal", "flying"], rentals: { pika_cup: { hp: 44, atk: 28, def: 25, spc: 26, spd: 27, moves: ["Sand-attack", "Fury Attack", "Fly", "Reflect"] }}},
    {id: "086", name: "Seel", types: ["water"], rentals: { pika_cup: { hp: 48, atk: 22, def: 25, spc: 30, spd: 22, moves: ["Surf", "Headbutt", "Horn Drill", "Blizzard"] }}},
    {id: "090", name: "Shellder", types: ["water"], rentals: { pika_cup: { hp: 38, atk: 28, def: 39, spc: 22, spd: 21, moves: ["Blizzard", "Tri Attack", "Explosion", "Surf"] }}},
    {id: "091", name: "Cloyster", types: ["water", "ice"], rentals: { pika_cup: { hp: 44, atk: 37, def: 63, spc: 34, spd: 30, moves: ["Supersonic", "Clamp", "Hyper Beam", "Aurora Beam"] }}},
    {id: "092", name: "Gastly", types: ["ghost", "poison"], rentals: { pika_cup: { hp: 38, atk: 19, def: 18, spc: 39, spd: 33, moves: ["Confuse Ray", "Psychic", "Night Shade", "Explosion"] }}},
    {id: "093", name: "Haunter", types: ["ghost", "poison"], rentals: { pika_cup: { hp: 42, atk: 24, def: 22, spc: 43, spd: 37, moves: ["Confuse Ray", "Thunderbolt", "Night Shade", "Selfdestruct"] }}},
    {id: "094", name: "Gengar", types: ["ghost", "poison"], rentals: { pika_cup: { hp: 47, atk: 28, def: 27, spc: 48, spd: 42, moves: ["Confuse Ray", "Night Shade", "Mega Drain", "Metronome"] }}},
    {id: "095", name: "Onix", types: ["rock", "ground"], rentals: { pika_cup: { hp: 39, atk: 22, def: 57, spc: 18, spd: 30, moves: ["Rock Slide", "Strength", "Earthquake", "Selfdestruct"] }}},
    {id: "096", name: "Drowzee", types: ["psychic"], rentals: { pika_cup: { hp: 47, atk: 23, def: 22, spc: 36, spd: 21, moves: ["Hypnosis", "Psychic", "Dream Eater", "Tri Attack"] }}},
    {id: "098", name: "Krabby", types: ["water"], rentals: { pika_cup: { hp: 38, atk: 40, def: 36, spc: 16, spd: 24, moves: ["Ice Beam", "Body Slam", "Surf", "Toxic"] }}},
    {id: "099", name: "Kingler", types: ["water"], rentals: { pika_cup: { hp: 45, atk: 48, def: 43, spc: 24, spd: 31, moves: ["Surf", "Strength", "Double Team", "Mimic"] }}},
    {id: "100", name: "Voltorb", types: ["electric"], rentals: { pika_cup: { hp: 41, atk: 18, def: 24, spc: 25, spd: 39, moves: ["Explosion", "Take Down", "Thunderbolt", "Thunder Wave"] }}},
    {id: "102", name: "Exeggcute", types: ["grass", "psychic"], rentals: { pika_cup: { hp: 47, atk: 21, def: 33, spc: 27, spd: 21, moves: ["Psychic", "Double Team", "Egg Bomb", "Toxic"] }}},
    {id: "103", name: "Exeggutor", types: ["grass", "psychic"], rentals: { pika_cup: { hp: 57, atk: 37, def: 34, spc: 46, spd: 25, moves: ["Toxic", "Barrage", "Mega Drain", "Psywave"] }}},
    {id: "104", name: "Cubone", types: ["ground"], rentals: { pika_cup: { hp: 44, atk: 24, def: 37, spc: 21, spd: 19, moves: ["Strength", "Blizzard", "Earthquake", "Tail Whip"] }}},
    {id: "108", name: "Lickitung", types: ["normal"], rentals: { pika_cup: { hp: 56, atk: 25, def: 31, spc: 27, spd: 18, moves: ["Double-edge", "Supersonic", "Fire Blast", "Thunder"] }}},
    {id: "109", name: "Koffing", types: ["poison"], rentals: { pika_cup: { hp: 41, atk: 28, def: 37, spc: 27, spd: 19, moves: ["Fire Blast", "Toxic", "Thunderbolt", "Selfdestruct"] }}},
    {id: "111", name: "Rhyhorn", types: ["ground", "rock"], rentals: { pika_cup: { hp: 53, atk: 34, def: 37, spc: 18, spd: 16, moves: ["Rock Slide", "Earthquake", "Horn Attack", "Substitute"] }}},
    {id: "113", name: "Chansey", types: ["normal"], rentals: { pika_cup: { hp: 104, atk: 10, def: 10, spc: 40, spd: 24, moves: ["Tri Attack", "Counter", "Bubblebeam", "Thunderbolt"] }}},
    {id: "116", name: "Horsea", types: ["water"], rentals: { pika_cup: { hp: 38, atk: 21, def: 30, spc: 30, spd: 27, moves: ["Surf", "Blizzard", "Toxic", "Swift"] }}},
    {id: "117", name: "Seadra", types: ["water"], rentals: { pika_cup: { hp: 45, atk: 28, def: 37, spc: 37, spd: 34, moves: ["Smokescreen", "Bubblebeam", "Ice Beam", "Mimic"] }}},
    {id: "118", name: "Goldeen", types: ["water"], rentals: { pika_cup: { hp: 42, atk: 29, def: 27, spc: 24, spd: 28, moves: ["Surf", "Double-edge", "Ice Beam", "Horn Drill"] }}},
    {id: "120", name: "Staryu", types: ["water"], rentals: { pika_cup: { hp: 38, atk: 22, def: 25, spc: 30, spd: 34, moves: ["Surf", "Psychic", "Tri Attack", "Thunder Wave"] }}},
    {id: "121", name: "Starmie", types: ["water", "psychic"], rentals: { pika_cup: { hp: 47, atk: 31, def: 34, spc: 39, spd: 43, moves: ["Psywave", "Bubblebeam", "Thunder", "Substitute"] }}},
    {id: "122", name: "Mr. Mime", types: ["psychic"], rentals: { pika_cup: { hp: 41, atk: 22, def: 28, spc: 39, spd: 36, moves: ["Mega Kick", "Psychic", "Barrier", "Metronome"] }}},
    {id: "123", name: "Scyther", types: ["bug", "flying"], rentals: { pika_cup: { hp: 50, atk: 42, def: 33, spc: 25, spd: 40, moves: ["Quick Attack", "Swords Dance", "Hyper Beam", "Double Team"] }}},
    {id: "127", name: "Pinsir", types: ["bug"], rentals: { pika_cup: { hp: 48, atk: 46, def: 39, spc: 25, spd: 34, moves: ["Take Down", "Submission", "Bide", "Mimic"] }}},
    {id: "129", name: "Magikarp", types: ["water"], rentals: { pika_cup: { hp: 35, atk: 12, def: 25, spc: 15, spd: 33, moves: ["Splash", "Tackle"] }}},
    {id: "130", name: "Gyarados", types: ["water", "flying"], rentals: { pika_cup: { hp: 57, atk: 46, def: 32, spc: 39, spd: 33, moves: ["Hydro Pump", "Bite", "Rest", "Leer"] }}},
    {id: "131", name: "Lapras", types: ["water", "ice"], rentals: { pika_cup: { hp: 68, atk: 34, def: 33, spc: 37, spd: 27, moves: ["Bubblebeam", "Ice Beam", "Growl", "Skull Bash"] }}},
    {id: "132", name: "Ditto", types: ["normal"], rentals: { pika_cup: { hp: 43, atk: 23, def: 23, spc: 23, spd: 23, moves: ["Transform"] }}},
    {id: "137", name: "Porygon", types: ["normal"], rentals: { pika_cup: { hp: 48, atk: 27, def: 30, spc: 31, spd: 21, moves: ["Conversion", "Sharpen", "Psychic", "Tri Attack"] }}},
    {id: "147", name: "Dratini", types: ["dragon"], rentals: { pika_cup: { hp: 41, atk: 28, def: 22, spc: 24, spd: 24, moves: ["Fire Blast", "Blizzard", "Body Slam", "Thunder Wave"] }}}
];